"""add admin users and optimistic store version

Revision ID: 0001_admin_store
Revises:
"""

from alembic import op


revision = "0001_admin_store"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE stores ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS admin_users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            display_name VARCHAR(100) NOT NULL,
            role VARCHAR(50) NOT NULL DEFAULT 'store_admin',
            status VARCHAR(20) NOT NULL DEFAULT 'active',
            last_login_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT ck_admin_users_role CHECK (role IN ('store_admin')),
            CONSTRAINT ck_admin_users_status CHECK (status IN ('active', 'disabled'))
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_admin_users_status ON admin_users(status)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_admin_users_status")
    op.execute("DROP TABLE IF EXISTS admin_users")
    op.execute("ALTER TABLE stores DROP COLUMN IF EXISTS version")
