"""add schools and associate stores with a school

Revision ID: 0002_schools
Revises: 0001_admin_store
"""

from alembic import op


revision = "0002_schools"
down_revision = "0001_admin_store"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS schools (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            school_code VARCHAR(100) NOT NULL UNIQUE,
            name VARCHAR(150) NOT NULL,
            city VARCHAR(60),
            district VARCHAR(60),
            address VARCHAR(255),
            latitude NUMERIC(9, 6),
            longitude NUMERIC(9, 6),
            status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute("ALTER TABLE stores ADD COLUMN IF NOT EXISTS school_id BIGINT")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'fk_stores_school_id'
            ) THEN
                ALTER TABLE stores
                    ADD CONSTRAINT fk_stores_school_id
                    FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT;
            END IF;
        END $$;
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_stores_school_id ON stores(school_id)")
    op.execute("DROP TRIGGER IF EXISTS trg_schools_updated_at ON schools")
    op.execute(
        """
        CREATE TRIGGER trg_schools_updated_at BEFORE UPDATE ON schools
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
        """
    )
    op.execute("DROP VIEW IF EXISTS store_catalog")
    op.execute(
        """
        CREATE VIEW store_catalog AS
        SELECT
            s.id,
            s.slug,
            s.school_id,
            sc.school_code,
            sc.name AS school_name,
            s.name,
            s.description,
            s.city,
            s.district,
            s.address,
            COALESCE(STRING_AGG(DISTINCT c.name, ' / ' ORDER BY c.name), '') AS categories,
            ROUND(COALESCE(AVG(r.rating), 0)::NUMERIC, 1) AS score,
            COUNT(DISTINCT r.id) AS review_count,
            m.bucket AS image_bucket,
            m.object_key AS image_object_key
        FROM stores s
        LEFT JOIN schools sc ON sc.id = s.school_id
        LEFT JOIN store_category_links scl ON scl.store_id = s.id
        LEFT JOIN store_categories c ON c.id = scl.category_id
        LEFT JOIN reviews r ON r.store_id = s.id AND r.status = 'published'
        LEFT JOIN store_images si ON si.store_id = s.id AND si.is_primary
        LEFT JOIN media_objects m ON m.id = si.media_id
        WHERE s.status = 'active'
        GROUP BY s.id, sc.school_code, sc.name, m.bucket, m.object_key
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS store_catalog")
    op.execute("DROP INDEX IF EXISTS idx_stores_school_id")
    op.execute("ALTER TABLE stores DROP CONSTRAINT IF EXISTS fk_stores_school_id")
    op.execute("ALTER TABLE stores DROP COLUMN IF EXISTS school_id")
    op.execute("DROP TABLE IF EXISTS schools")
