"""persist users, favorites, photo check-ins, and review prerequisites

Revision ID: 0004_user_actions
Revises: 0003_store_area
"""

from alembic import op


revision = "0004_user_actions"
down_revision = "0003_store_area"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS school_id BIGINT")
    op.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_app_users_school_id') THEN
                ALTER TABLE app_users
                    ADD CONSTRAINT fk_app_users_school_id
                    FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
            END IF;
        END $$
        """
    )

    op.execute("ALTER TABLE media_objects ADD COLUMN IF NOT EXISTS owner_user_id BIGINT")
    op.execute("ALTER TABLE media_objects ADD COLUMN IF NOT EXISTS purpose VARCHAR(30) NOT NULL DEFAULT 'system'")
    op.execute("ALTER TABLE media_objects ADD COLUMN IF NOT EXISTS upload_state VARCHAR(20) NOT NULL DEFAULT 'attached'")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_media_objects_owner_user_id') THEN
                ALTER TABLE media_objects
                    ADD CONSTRAINT fk_media_objects_owner_user_id
                    FOREIGN KEY (owner_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
            END IF;
        END $$
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_media_objects_owner_purpose ON media_objects(owner_user_id, purpose)")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_favorites (
            user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
            store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (user_id, store_id)
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_user_favorites_store ON user_favorites(store_id, created_at DESC)")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS check_ins (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
            store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
            photo_media_id BIGINT NOT NULL REFERENCES media_objects(id) ON DELETE RESTRICT,
            note VARCHAR(500),
            checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_check_in_photo UNIQUE (photo_media_id),
            CONSTRAINT uq_check_in_identity UNIQUE (id, user_id, store_id)
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_check_ins_user_time ON check_ins(user_id, checked_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_check_ins_store_time ON check_ins(store_id, checked_at DESC)")

    op.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS check_in_id BIGINT")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_check_in_id') THEN
                ALTER TABLE reviews
                    ADD CONSTRAINT fk_reviews_check_in_id
                    FOREIGN KEY (check_in_id) REFERENCES check_ins(id) ON DELETE SET NULL;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_check_in_identity') THEN
                ALTER TABLE reviews
                    ADD CONSTRAINT fk_reviews_check_in_identity
                    FOREIGN KEY (check_in_id, user_id, store_id)
                    REFERENCES check_ins(id, user_id, store_id);
            END IF;
        END $$
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_reviews_check_in ON reviews(check_in_id)")

    op.execute(
        """
        DO $$
        BEGIN
            IF to_regclass('public.user_store_states') IS NOT NULL THEN
                INSERT INTO user_favorites (user_id, store_id, created_at)
                SELECT user_id, store_id, COALESCE(favorited_at, created_at)
                FROM user_store_states
                WHERE is_favorite
                ON CONFLICT (user_id, store_id) DO NOTHING;
            END IF;
        END $$
        """
    )

    op.execute("DROP TRIGGER IF EXISTS trg_check_ins_updated_at ON check_ins")
    op.execute(
        """
        CREATE TRIGGER trg_check_ins_updated_at BEFORE UPDATE ON check_ins
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
        """
    )
    op.execute("DROP TABLE IF EXISTS user_store_states")


def downgrade() -> None:
    op.execute("CREATE TABLE IF NOT EXISTS user_store_states (user_id BIGINT NOT NULL, store_id BIGINT NOT NULL, is_favorite BOOLEAN NOT NULL DEFAULT FALSE, is_eaten BOOLEAN NOT NULL DEFAULT FALSE, favorited_at TIMESTAMPTZ, eaten_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, store_id))")
    op.execute("DROP INDEX IF EXISTS idx_reviews_check_in")
    op.execute("ALTER TABLE reviews DROP CONSTRAINT IF EXISTS fk_reviews_check_in_identity")
    op.execute("ALTER TABLE reviews DROP CONSTRAINT IF EXISTS fk_reviews_check_in_id")
    op.execute("ALTER TABLE reviews DROP COLUMN IF EXISTS check_in_id")
    op.execute("DROP TABLE IF EXISTS check_ins")
    op.execute("DROP INDEX IF EXISTS idx_user_favorites_store")
    op.execute("DROP TABLE IF EXISTS user_favorites")
    op.execute("DROP INDEX IF EXISTS idx_media_objects_owner_purpose")
    op.execute("ALTER TABLE media_objects DROP CONSTRAINT IF EXISTS fk_media_objects_owner_user_id")
    op.execute("ALTER TABLE media_objects DROP COLUMN IF EXISTS upload_state")
    op.execute("ALTER TABLE media_objects DROP COLUMN IF EXISTS purpose")
    op.execute("ALTER TABLE media_objects DROP COLUMN IF EXISTS owner_user_id")
    op.execute("ALTER TABLE app_users DROP CONSTRAINT IF EXISTS fk_app_users_school_id")
    op.execute("ALTER TABLE app_users DROP COLUMN IF EXISTS last_login_at")
    op.execute("ALTER TABLE app_users DROP COLUMN IF EXISTS school_id")
