"""规范化学校区域与店铺目录

Revision ID: 0005_store_catalog
Revises: 0004_user_actions
"""

from alembic import op


revision = "0005_store_catalog"
down_revision = "0004_user_actions"
branch_labels = None
depends_on = None


def _create_catalog_view() -> None:
    op.execute(
        """
        CREATE VIEW store_catalog AS
        SELECT
            s.id,
            s.store_code,
            s.school_id,
            sc.school_code,
            sc.name AS school_name,
            s.area_id,
            sa.area_code,
            sa.name AS area_name,
            s.name,
            s.description,
            s.city,
            s.district,
            s.address,
            s.latitude,
            s.longitude,
            s.phone,
            s.business_hours,
            COALESCE(category_stats.categories, '') AS categories,
            review_stats.score,
            COALESCE(review_stats.review_count, 0) AS review_count,
            COALESCE(favorite_stats.favorite_count, 0) AS favorite_count,
            m.bucket AS image_bucket,
            m.object_key AS image_object_key
        FROM stores s
        JOIN schools sc ON sc.id = s.school_id
        JOIN school_areas sa ON sa.id = s.area_id AND sa.school_id = s.school_id
        LEFT JOIN LATERAL (
            SELECT STRING_AGG(c.name, ' / ' ORDER BY c.name) AS categories
            FROM store_category_links scl
            JOIN store_categories c ON c.id = scl.category_id
            WHERE scl.store_id = s.id
        ) category_stats ON TRUE
        LEFT JOIN LATERAL (
            SELECT
                ROUND(AVG(r.rating)::NUMERIC, 1) AS score,
                COUNT(*) AS review_count
            FROM reviews r
            WHERE r.store_id = s.id AND r.status = 'published'
        ) review_stats ON TRUE
        LEFT JOIN LATERAL (
            SELECT COUNT(*) AS favorite_count
            FROM user_favorites uf
            WHERE uf.store_id = s.id
        ) favorite_stats ON TRUE
        LEFT JOIN store_images si ON si.store_id = s.id AND si.is_primary
        LEFT JOIN media_objects m ON m.id = si.media_id
        WHERE s.status = 'active'
        """
    )


def upgrade() -> None:
    op.execute("DROP VIEW IF EXISTS store_catalog")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM stores WHERE school_id IS NULL) THEN
                RAISE EXCEPTION '无法规范化店铺：存在未关联学校的店铺';
            END IF;
        END $$
        """
    )
    op.execute(
        """
        CREATE TABLE school_areas (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
            area_code VARCHAR(100) NOT NULL,
            name VARCHAR(100) NOT NULL,
            description VARCHAR(500),
            sort_order SMALLINT NOT NULL DEFAULT 0,
            status VARCHAR(20) NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT ck_school_areas_code_format
                CHECK (area_code ~ '^[a-z0-9][a-z0-9_-]{1,99}$'),
            CONSTRAINT ck_school_areas_name_not_blank CHECK (BTRIM(name) <> ''),
            CONSTRAINT ck_school_areas_sort_order CHECK (sort_order >= 0),
            CONSTRAINT ck_school_areas_status CHECK (status IN ('active', 'hidden')),
            CONSTRAINT uq_school_areas_school_code UNIQUE (school_id, area_code),
            CONSTRAINT uq_school_areas_school_name UNIQUE (school_id, name),
            CONSTRAINT uq_school_areas_school_id_id UNIQUE (school_id, id)
        )
        """
    )
    op.execute(
        "CREATE INDEX idx_school_areas_school_status_sort "
        "ON school_areas(school_id, status, sort_order, id)"
    )
    op.execute(
        """
        CREATE TRIGGER trg_school_areas_updated_at BEFORE UPDATE ON school_areas
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'stores' AND column_name = 'slug'
            ) THEN
                ALTER TABLE stores RENAME COLUMN slug TO store_code;
            END IF;
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'stores'::regclass AND conname = 'stores_slug_key'
            ) THEN
                ALTER TABLE stores RENAME CONSTRAINT stores_slug_key TO uq_stores_store_code;
            END IF;
        END $$
        """
    )
    op.execute("ALTER TABLE stores ADD COLUMN area_id BIGINT")
    op.execute("ALTER TABLE stores ADD COLUMN latitude NUMERIC(9, 6)")
    op.execute("ALTER TABLE stores ADD COLUMN longitude NUMERIC(9, 6)")
    op.execute("ALTER TABLE stores ADD COLUMN phone VARCHAR(40)")
    op.execute("ALTER TABLE stores ADD COLUMN business_hours JSONB NOT NULL DEFAULT '{}'::JSONB")

    op.execute(
        """
        INSERT INTO school_areas (school_id, area_code, name, sort_order)
        SELECT DISTINCT
            school_id,
            'legacy-' || SUBSTRING(MD5(LOWER(COALESCE(NULLIF(BTRIM(area), ''), '未分类区域'))) FROM 1 FOR 12),
            COALESCE(NULLIF(BTRIM(area), ''), '未分类区域'),
            100
        FROM stores
        ON CONFLICT (school_id, name) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE stores s
        SET area_id = sa.id
        FROM school_areas sa
        WHERE sa.school_id = s.school_id
          AND sa.name = COALESCE(NULLIF(BTRIM(s.area), ''), '未分类区域')
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM stores WHERE area_id IS NULL) THEN
                RAISE EXCEPTION '无法规范化店铺：存在未匹配区域的店铺';
            END IF;
        END $$
        """
    )
    op.execute("ALTER TABLE stores ALTER COLUMN school_id SET NOT NULL")
    op.execute("ALTER TABLE stores ALTER COLUMN area_id SET NOT NULL")
    op.execute(
        """
        ALTER TABLE stores
        ADD CONSTRAINT fk_stores_school_area
        FOREIGN KEY (school_id, area_id)
        REFERENCES school_areas(school_id, id)
        ON DELETE RESTRICT
        """
    )
    op.execute(
        "ALTER TABLE stores ADD CONSTRAINT ck_stores_store_code_format "
        "CHECK (store_code ~ '^[a-z0-9][a-z0-9_-]{1,99}$')"
    )
    op.execute(
        "ALTER TABLE stores ADD CONSTRAINT ck_stores_latitude_range "
        "CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90)"
    )
    op.execute(
        "ALTER TABLE stores ADD CONSTRAINT ck_stores_longitude_range "
        "CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)"
    )
    op.execute(
        "ALTER TABLE stores ADD CONSTRAINT ck_stores_business_hours_object "
        "CHECK (JSONB_TYPEOF(business_hours) = 'object')"
    )
    op.execute("ALTER TABLE stores DROP COLUMN area")
    op.execute(
        "CREATE INDEX idx_stores_school_area_status "
        "ON stores(school_id, area_id, status, updated_at DESC, id DESC)"
    )
    _create_catalog_view()


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS store_catalog")
    op.execute("ALTER TABLE stores ADD COLUMN area VARCHAR(100) NOT NULL DEFAULT ''")
    op.execute(
        """
        UPDATE stores s
        SET area = sa.name
        FROM school_areas sa
        WHERE sa.id = s.area_id AND sa.school_id = s.school_id
        """
    )
    op.execute("DROP INDEX IF EXISTS idx_stores_school_area_status")
    op.execute("ALTER TABLE stores DROP CONSTRAINT IF EXISTS ck_stores_business_hours_object")
    op.execute("ALTER TABLE stores DROP CONSTRAINT IF EXISTS ck_stores_longitude_range")
    op.execute("ALTER TABLE stores DROP CONSTRAINT IF EXISTS ck_stores_latitude_range")
    op.execute("ALTER TABLE stores DROP CONSTRAINT IF EXISTS ck_stores_store_code_format")
    op.execute("ALTER TABLE stores DROP CONSTRAINT IF EXISTS fk_stores_school_area")
    op.execute("ALTER TABLE stores ALTER COLUMN school_id DROP NOT NULL")
    op.execute("ALTER TABLE stores DROP COLUMN business_hours")
    op.execute("ALTER TABLE stores DROP COLUMN phone")
    op.execute("ALTER TABLE stores DROP COLUMN longitude")
    op.execute("ALTER TABLE stores DROP COLUMN latitude")
    op.execute("ALTER TABLE stores DROP COLUMN area_id")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'stores'::regclass AND conname = 'uq_stores_store_code'
            ) THEN
                ALTER TABLE stores RENAME CONSTRAINT uq_stores_store_code TO stores_slug_key;
            END IF;
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'stores' AND column_name = 'store_code'
            ) THEN
                ALTER TABLE stores RENAME COLUMN store_code TO slug;
            END IF;
        END $$
        """
    )
    op.execute("DROP TABLE school_areas")
    op.execute(
        """
        CREATE VIEW store_catalog AS
        SELECT
            s.id,
            s.slug,
            s.school_id,
            sc.school_code,
            sc.name AS school_name,
            s.name,
            s.description,
            s.city,
            s.district,
            s.address,
            s.area,
            COALESCE(STRING_AGG(DISTINCT c.name, ' / ' ORDER BY c.name), '') AS categories,
            ROUND(COALESCE(AVG(r.rating), 0)::NUMERIC, 1) AS score,
            COUNT(DISTINCT r.id) AS review_count,
            m.bucket AS image_bucket,
            m.object_key AS image_object_key
        FROM stores s
        LEFT JOIN schools sc ON sc.id = s.school_id
        LEFT JOIN store_category_links scl ON scl.store_id = s.id
        LEFT JOIN store_categories c ON c.id = scl.category_id
        LEFT JOIN reviews r ON r.store_id = s.id AND r.status = 'published'
        LEFT JOIN store_images si ON si.store_id = s.id AND si.is_primary
        LEFT JOIN media_objects m ON m.id = si.media_id
        WHERE s.status = 'active'
        GROUP BY s.id, sc.school_code, sc.name, m.bucket, m.object_key
        """
    )
