"""新增多学校管理员、用户限制、内容治理与审计日志

Revision ID: 0006_admin_governance
Revises: 0005_store_catalog
"""

from alembic import op


revision = "0006_admin_governance"
down_revision = "0005_store_catalog"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE admin_users DROP CONSTRAINT IF EXISTS ck_admin_users_role")
    op.execute(
        "ALTER TABLE admin_users ADD CONSTRAINT ck_admin_users_role "
        "CHECK (role IN ('store_admin', 'platform_admin', 'school_admin'))"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS admin_user_schools (
            admin_user_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
            school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (admin_user_id, school_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_restrictions (
            user_id BIGINT PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
            comment_blocked BOOLEAN NOT NULL DEFAULT FALSE,
            comment_block_reason VARCHAR(500),
            comment_blocked_until TIMESTAMPTZ,
            image_upload_blocked BOOLEAN NOT NULL DEFAULT FALSE,
            image_upload_block_reason VARCHAR(500),
            image_upload_blocked_until TIMESTAMPTZ,
            updated_by BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS moderation_reason VARCHAR(500)")
    op.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS moderated_by BIGINT REFERENCES admin_users(id) ON DELETE SET NULL")
    op.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMPTZ")
    op.execute("ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS school_id BIGINT REFERENCES schools(id) ON DELETE RESTRICT")
    op.execute("UPDATE check_ins c SET school_id = s.school_id FROM stores s WHERE c.store_id = s.id AND c.school_id IS NULL")
    op.execute("ALTER TABLE check_ins ALTER COLUMN school_id SET NOT NULL")
    op.execute("ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'published'")
    op.execute("ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS moderation_reason VARCHAR(500)")
    op.execute("ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS moderated_by BIGINT REFERENCES admin_users(id) ON DELETE SET NULL")
    op.execute("ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMPTZ")
    op.execute("ALTER TABLE check_ins DROP CONSTRAINT IF EXISTS ck_check_ins_status")
    op.execute("ALTER TABLE check_ins ADD CONSTRAINT ck_check_ins_status CHECK (status IN ('published', 'hidden'))")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS admin_audit_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
            school_id BIGINT REFERENCES schools(id) ON DELETE SET NULL,
            action VARCHAR(80) NOT NULL,
            target_type VARCHAR(50) NOT NULL,
            target_id VARCHAR(100) NOT NULL,
            reason VARCHAR(500),
            before_data JSONB,
            after_data JSONB,
            ip_address VARCHAR(64),
            user_agent VARCHAR(500),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_admin_user_schools_school ON admin_user_schools(school_id, admin_user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_time ON admin_audit_logs(created_at DESC, id DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_school ON admin_audit_logs(school_id, created_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_check_ins_school_status_time ON check_ins(school_id, status, checked_at DESC)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS admin_audit_logs")
    op.execute("ALTER TABLE check_ins DROP COLUMN IF EXISTS moderated_at")
    op.execute("ALTER TABLE check_ins DROP COLUMN IF EXISTS moderated_by")
    op.execute("ALTER TABLE check_ins DROP COLUMN IF EXISTS moderation_reason")
    op.execute("ALTER TABLE check_ins DROP COLUMN IF EXISTS status")
    op.execute("ALTER TABLE check_ins DROP COLUMN IF EXISTS school_id")
    op.execute("ALTER TABLE reviews DROP COLUMN IF EXISTS moderated_at")
    op.execute("ALTER TABLE reviews DROP COLUMN IF EXISTS moderated_by")
    op.execute("ALTER TABLE reviews DROP COLUMN IF EXISTS moderation_reason")
    op.execute("DROP TABLE IF EXISTS user_restrictions")
    op.execute("DROP TABLE IF EXISTS admin_user_schools")
    op.execute("ALTER TABLE admin_users DROP CONSTRAINT IF EXISTS ck_admin_users_role")
    op.execute("ALTER TABLE admin_users ADD CONSTRAINT ck_admin_users_role CHECK (role IN ('store_admin'))")
