"""新增平台通知、公告、已读状态与微信发送队列。"""

from alembic import op


revision = "0008_platform_messages"
down_revision = "0007_draw_performance_indexes"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE platform_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind VARCHAR(20) NOT NULL CHECK (kind IN ('notification', 'announcement')),
            source VARCHAR(20) NOT NULL DEFAULT 'admin' CHECK (source IN ('admin', 'system')),
            event_type VARCHAR(80), title VARCHAR(120) NOT NULL, body_html TEXT NOT NULL,
            target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('all', 'school', 'user')),
            school_id BIGINT REFERENCES schools(id) ON DELETE SET NULL,
            user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
            priority VARCHAR(20) NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'important')),
            status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'revoked')),
            action_type VARCHAR(30), action_target_id BIGINT,
            wechat_push BOOLEAN NOT NULL DEFAULT FALSE,
            publish_at TIMESTAMPTZ, expire_at TIMESTAMPTZ, published_at TIMESTAMPTZ,
            revoked_at TIMESTAMPTZ, dispatch_prepared_at TIMESTAMPTZ,
            created_by BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
            updated_by BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT ck_platform_messages_target CHECK (
                (target_type = 'all' AND school_id IS NULL AND user_id IS NULL) OR
                (target_type = 'school' AND school_id IS NOT NULL AND user_id IS NULL) OR
                (target_type = 'user' AND user_id IS NOT NULL AND school_id IS NULL)
            ),
            CONSTRAINT ck_platform_messages_expiry CHECK (expire_at IS NULL OR publish_at IS NULL OR expire_at > publish_at)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE message_media_links (
            message_id BIGINT NOT NULL REFERENCES platform_messages(id) ON DELETE CASCADE,
            media_id BIGINT NOT NULL REFERENCES media_objects(id) ON DELETE RESTRICT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (message_id, media_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE message_read_states (
            message_id BIGINT NOT NULL REFERENCES platform_messages(id) ON DELETE CASCADE,
            user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
            read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (message_id, user_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE user_wechat_subscriptions (
            user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
            template_kind VARCHAR(20) NOT NULL CHECK (template_kind IN ('notification', 'announcement')),
            status VARCHAR(20) NOT NULL DEFAULT 'unknown' CHECK (status IN ('unknown', 'accepted', 'rejected', 'banned', 'consumed', 'needs_reauth')),
            enabled BOOLEAN NOT NULL DEFAULT TRUE, consented_at TIMESTAMPTZ, last_sent_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, template_kind)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE wechat_delivery_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message_id BIGINT NOT NULL REFERENCES platform_messages(id) ON DELETE CASCADE,
            user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
            template_kind VARCHAR(20) NOT NULL CHECK (template_kind IN ('notification', 'announcement')),
            status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'sent', 'retry', 'failed', 'skipped')),
            attempts SMALLINT NOT NULL DEFAULT 0, next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_error_code VARCHAR(80), last_error_message VARCHAR(500), sent_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_wechat_delivery_message_user UNIQUE (message_id, user_id)
        )
        """
    )
    op.execute("CREATE INDEX idx_platform_messages_user_time ON platform_messages(user_id, publish_at DESC) WHERE status = 'published'")
    op.execute("CREATE INDEX idx_platform_messages_school_time ON platform_messages(school_id, publish_at DESC) WHERE status = 'published'")
    op.execute("CREATE INDEX idx_platform_messages_active ON platform_messages(kind, publish_at DESC) WHERE status = 'published'")
    op.execute("CREATE INDEX idx_message_reads_user ON message_read_states(user_id, read_at DESC)")
    op.execute("CREATE INDEX idx_wechat_jobs_ready ON wechat_delivery_jobs(status, next_attempt_at, id)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS wechat_delivery_jobs")
    op.execute("DROP TABLE IF EXISTS user_wechat_subscriptions")
    op.execute("DROP TABLE IF EXISTS message_read_states")
    op.execute("DROP TABLE IF EXISTS message_media_links")
    op.execute("DROP TABLE IF EXISTS platform_messages")
