"""新增学校天气缓存并回填武汉工商学院坐标。"""

from alembic import op


revision = "0011_school_weather_daily"
down_revision = "0010_confirmed_pick_history"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # baseline 也包含本表，使用 IF NOT EXISTS 兼容全新数据卷从 0006 继续升级。
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS school_weather_daily (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
            forecast_date DATE NOT NULL,
            temperature_min NUMERIC(5, 2) NOT NULL,
            temperature_max NUMERIC(5, 2) NOT NULL,
            weather_code VARCHAR(32) NOT NULL,
            weather_text VARCHAR(80) NOT NULL,
            icon VARCHAR(16) NOT NULL,
            provider VARCHAR(30) NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_school_weather_daily_school_date
                UNIQUE (school_id, forecast_date),
            CONSTRAINT ck_school_weather_daily_temperature
                CHECK (temperature_min <= temperature_max),
            CONSTRAINT ck_school_weather_daily_provider
                CHECK (provider IN ('open_meteo', 'qweather'))
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_school_weather_daily_date "
        "ON school_weather_daily(forecast_date, school_id)"
    )
    op.execute(
        """
        UPDATE schools
        SET latitude = 30.460717,
            longitude = 114.268004,
            updated_at = NOW()
        WHERE school_code = 'wtbu'
          AND (latitude IS NULL OR longitude IS NULL)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS school_weather_daily")
    # 只撤销由本迁移写入且未被管理员再次调整的坐标。
    op.execute(
        """
        UPDATE schools
        SET latitude = NULL,
            longitude = NULL,
            updated_at = NOW()
        WHERE school_code = 'wtbu'
          AND latitude = 30.460717
          AND longitude = 114.268004
        """
    )
