BEGIN;

CREATE TABLE IF NOT EXISTS media_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket VARCHAR(128) NOT NULL,
    object_key TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes >= 0),
    width INTEGER CHECK (width IS NULL OR width > 0),
    height INTEGER CHECK (height IS NULL OR height > 0),
    checksum_sha256 CHAR(64),
    source_provider VARCHAR(64),
    source_url TEXT,
    license_name VARCHAR(128),
    license_url TEXT,
    attribution_text TEXT,
    owner_user_id BIGINT,
    purpose VARCHAR(30) NOT NULL DEFAULT 'system',
    upload_state VARCHAR(20) NOT NULL DEFAULT 'attached',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_media_bucket_object_key UNIQUE (bucket, object_key)
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    nickname VARCHAR(80) NOT NULL,
    avatar_media_id BIGINT REFERENCES media_objects(id) ON DELETE SET NULL,
    slogan VARCHAR(255),
    level SMALLINT NOT NULL DEFAULT 1 CHECK (level >= 1),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS store_categories (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    city VARCHAR(60),
    district VARCHAR(60),
    address VARCHAR(255),
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS school_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
    area_code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL CHECK (BTRIM(name) <> ''),
    description VARCHAR(500),
    sort_order SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_school_areas_code_format CHECK (area_code ~ '^[a-z0-9][a-z0-9_-]{1,99}$'),
    CONSTRAINT uq_school_areas_school_code UNIQUE (school_id, area_code),
    CONSTRAINT uq_school_areas_school_name UNIQUE (school_id, name),
    CONSTRAINT uq_school_areas_school_id_id UNIQUE (school_id, id)
);

ALTER TABLE app_users ADD COLUMN IF NOT EXISTS school_id BIGINT;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE media_objects ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE media_objects ADD COLUMN IF NOT EXISTS purpose VARCHAR(30) NOT NULL DEFAULT 'system';
ALTER TABLE media_objects ADD COLUMN IF NOT EXISTS upload_state VARCHAR(20) NOT NULL DEFAULT 'attached';
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_app_users_school_id') THEN
        ALTER TABLE app_users ADD CONSTRAINT fk_app_users_school_id FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_media_objects_owner_user_id') THEN
        ALTER TABLE media_objects ADD CONSTRAINT fk_media_objects_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code VARCHAR(100) NOT NULL CONSTRAINT uq_stores_store_code UNIQUE,
    school_id BIGINT NOT NULL CONSTRAINT fk_stores_school_id REFERENCES schools(id) ON DELETE RESTRICT,
    area_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    city VARCHAR(60),
    district VARCHAR(60),
    address VARCHAR(255) NOT NULL,
    latitude NUMERIC(9, 6) CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    longitude NUMERIC(9, 6) CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    phone VARCHAR(40),
    business_hours JSONB NOT NULL DEFAULT '{}'::JSONB CHECK (JSONB_TYPEOF(business_hours) = 'object'),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden', 'closed')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_stores_store_code_format CHECK (store_code ~ '^[a-z0-9][a-z0-9_-]{1,99}$'),
    CONSTRAINT fk_stores_school_area FOREIGN KEY (school_id, area_id)
        REFERENCES school_areas(school_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS store_category_links (
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    category_id SMALLINT NOT NULL REFERENCES store_categories(id) ON DELETE RESTRICT,
    PRIMARY KEY (store_id, category_id)
);

CREATE TABLE IF NOT EXISTS store_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_objects(id) ON DELETE RESTRICT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_store_image UNIQUE (store_id, media_id)
);

CREATE TABLE IF NOT EXISTS user_favorites (
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, store_id)
);

CREATE TABLE IF NOT EXISTS check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    photo_media_id BIGINT NOT NULL REFERENCES media_objects(id) ON DELETE RESTRICT,
    note VARCHAR(500),
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_check_in_photo UNIQUE (photo_media_id),
    CONSTRAINT uq_check_in_identity UNIQUE (id, user_id, store_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_store_primary_image
    ON store_images(store_id) WHERE is_primary;

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    check_in_id BIGINT REFERENCES check_ins(id) ON DELETE SET NULL,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content TEXT NOT NULL,
    visited_at DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'hidden')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_review_user_store UNIQUE (user_id, store_id)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_check_in_identity') THEN
        ALTER TABLE reviews
            ADD CONSTRAINT fk_reviews_check_in_identity
            FOREIGN KEY (check_in_id, user_id, store_id)
            REFERENCES check_ins(id, user_id, store_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS review_images (
    review_id BIGINT NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_objects(id) ON DELETE RESTRICT,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (review_id, media_id)
);

CREATE TABLE IF NOT EXISTS activity_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(100) UNIQUE,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    action VARCHAR(30) NOT NULL CHECK (action IN ('random_pick', 'store_view')),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stores_status ON stores(status);
CREATE INDEX IF NOT EXISTS idx_stores_school_id ON stores(school_id);
CREATE INDEX IF NOT EXISTS idx_school_areas_school_status_sort ON school_areas(school_id, status, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_stores_school_area_status ON stores(school_id, area_id, status, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_stores_name_lower ON stores(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_store_category_links_category ON store_category_links(category_id, store_id);
CREATE INDEX IF NOT EXISTS idx_reviews_store_created ON reviews(store_id, created_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_activity_history_user_time ON activity_history(user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_favorites_store ON user_favorites(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_check_ins_user_time ON check_ins(user_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_check_ins_store_time ON check_ins(store_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_check_in ON reviews(check_in_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_media_objects_updated_at ON media_objects;
CREATE TRIGGER trg_media_objects_updated_at BEFORE UPDATE ON media_objects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_app_users_updated_at ON app_users;
CREATE TRIGGER trg_app_users_updated_at BEFORE UPDATE ON app_users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_stores_updated_at ON stores;
CREATE TRIGGER trg_stores_updated_at BEFORE UPDATE ON stores
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_schools_updated_at ON schools;
CREATE TRIGGER trg_schools_updated_at BEFORE UPDATE ON schools
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_school_areas_updated_at ON school_areas;
CREATE TRIGGER trg_school_areas_updated_at BEFORE UPDATE ON school_areas
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_reviews_updated_at ON reviews;
CREATE TRIGGER trg_reviews_updated_at BEFORE UPDATE ON reviews
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_check_ins_updated_at ON check_ins;
CREATE TRIGGER trg_check_ins_updated_at BEFORE UPDATE ON check_ins
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP VIEW IF EXISTS store_catalog;
CREATE VIEW store_catalog AS
SELECT
    s.id,
    s.store_code,
    s.school_id,
    sc.school_code,
    sc.name AS school_name,
    s.area_id,
    sa.area_code,
    sa.name AS area_name,
    s.name,
    s.description,
    s.city,
    s.district,
    s.address,
    s.latitude,
    s.longitude,
    s.phone,
    s.business_hours,
    COALESCE(category_stats.categories, '') AS categories,
    review_stats.score,
    COALESCE(review_stats.review_count, 0) AS review_count,
    COALESCE(favorite_stats.favorite_count, 0) AS favorite_count,
    m.bucket AS image_bucket,
    m.object_key AS image_object_key
FROM stores s
JOIN schools sc ON sc.id = s.school_id
JOIN school_areas sa ON sa.id = s.area_id AND sa.school_id = s.school_id
LEFT JOIN LATERAL (
    SELECT STRING_AGG(c.name, ' / ' ORDER BY c.name) AS categories
    FROM store_category_links scl
    JOIN store_categories c ON c.id = scl.category_id
    WHERE scl.store_id = s.id
) category_stats ON TRUE
LEFT JOIN LATERAL (
    SELECT ROUND(AVG(r.rating)::NUMERIC, 1) AS score, COUNT(*) AS review_count
    FROM reviews r
    WHERE r.store_id = s.id AND r.status = 'published'
) review_stats ON TRUE
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS favorite_count
    FROM user_favorites uf
    WHERE uf.store_id = s.id
) favorite_stats ON TRUE
LEFT JOIN store_images si ON si.store_id = s.id AND si.is_primary
LEFT JOIN media_objects m ON m.id = si.media_id
WHERE s.status = 'active';

COMMIT;
