<script setup lang="ts">
import { onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import { ref } from 'vue'
import PageHeader from '../../components/PageHeader.vue'
import EmptyState from '../../components/EmptyState.vue'
import { getMessages, markAllMessagesRead, type MessageItem, type MessageKind } from '../../api/messages'
import { useMessageStore } from '../../stores/useMessageStore'
import { ApiClientError } from '../../api/types'

const messageStore=useMessageStore();const rows=ref<MessageItem[]>([]);const loading=ref(true);const error=ref('');const activeKind=ref<''|MessageKind>('')
function format(value:string){return new Date(value).toLocaleString()}
async function load(refresh=false){loading.value=!refresh;error.value='';try{const data=await getMessages({kind:activeKind.value||undefined,page:1,pageSize:100});rows.value=data.items;await messageStore.refreshUnread()}catch(e){error.value=e instanceof ApiClientError?e.message:'消息加载失败'}finally{loading.value=false;if(refresh)uni.stopPullDownRefresh()}}
function choose(kind:''|MessageKind){activeKind.value=kind;void load()}
function open(item:MessageItem){uni.navigateTo({url:`/pages/messages/detail?id=${item.id}`})}
async function readAll(){try{await markAllMessagesRead(activeKind.value||undefined);rows.value=rows.value.map(item=>({...item,isRead:true}));await messageStore.refreshUnread();uni.showToast({title:'已全部标为已读',icon:'none'})}catch(e){uni.showToast({title:e instanceof ApiClientError?e.message:'操作失败',icon:'none'})}}
onShow(()=>void load());onPullDownRefresh(()=>void load(true))
</script>
<template><view class="page-shell messages-page"><PageHeader title="消息中心" back/><view class="page-pad"><view class="tabs"><view v-for="tab in [{v:'',l:'全部'},{v:'notification',l:'通知'},{v:'announcement',l:'公告'}]" :key="tab.v" class="tab" :class="{active:activeKind===tab.v}" @tap="choose(tab.v as any)">{{tab.l}}</view><button class="read-all" @tap="readAll">全部已读</button></view><view v-if="loading" class="state">正在整理消息…</view><view v-else-if="error" class="state"><text>{{error}}</text><button @tap="load()">重新加载</button></view><view v-else-if="rows.length" class="message-list"><view v-for="item in rows" :key="item.id" class="message-card" :class="{unread:!item.isRead,important:item.priority==='important'}" @tap="open(item)"><view class="message-head"><text class="kind">{{item.kind==='announcement'?'公告':'通知'}}</text><text class="time">{{format(item.publishAt)}}</text></view><text class="title">{{item.title}}</text><text class="hint">点击查看详情</text><view v-if="!item.isRead" class="unread-dot"/></view></view><EmptyState v-else title="暂时没有消息" description="有新通知时会出现在这里"/></view></view></template>
<style scoped>.page-pad{padding:24rpx 28rpx}.tabs{display:flex;align-items:center;gap:12rpx;margin-bottom:22rpx}.tab{padding:12rpx 24rpx;border:1rpx dashed var(--line);border-radius:10rpx;background:#fffaf0;color:var(--muted);font-size:25rpx}.tab.active{border-style:solid;border-color:var(--brand);background:var(--brand-soft);color:var(--brand-deep);font-weight:900}.read-all{margin-left:auto;color:var(--brand);font-size:24rpx}.state{display:flex;align-items:center;justify-content:center;min-height:480rpx;color:var(--muted);flex-direction:column}.state button{margin-top:20rpx;color:var(--brand)}.message-list{display:flex;flex-direction:column;gap:18rpx}.message-card{position:relative;padding:23rpx;border:1rpx solid var(--line);border-radius:9rpx 15rpx 10rpx 13rpx;background:#fffaf0;box-shadow:var(--paper-shadow)}.message-card.unread{border-color:#dc8d78;background:#fff5ec}.message-card.important{border-left:8rpx solid var(--brand)}.message-head{display:flex;justify-content:space-between}.kind{color:var(--brand);font-size:23rpx;font-weight:900}.time,.hint{color:var(--muted);font-size:21rpx}.title{display:block;margin:14rpx 0 10rpx;font-size:31rpx;font-weight:900}.unread-dot{position:absolute;top:20rpx;right:20rpx;width:15rpx;height:15rpx;border-radius:50%;background:var(--brand)}.message-head .time{margin-right:20rpx}</style>
