<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, type PageData } from '../api/client'
import AuthImage from '../components/AuthImage.vue'
import StatusSticker from '../components/StatusSticker.vue'
import { useWorkspaceStore } from '../stores/workspace'

interface CheckInItem{id:string;photoUrl:string;note?:string;status:string;moderationReason?:string;user:{id:string;nickname:string};store:{id:string;name:string};schoolName:string;checkedAt:string}
const workspace=useWorkspaceStore();const filters=reactive({status:'',page:1,pageSize:20});const rows=ref<CheckInItem[]>([]);const total=ref(0);const loading=ref(false);const selected=ref<CheckInItem[]>([]);const viewMode=ref<'table'|'grid'>('table')
async function load(){loading.value=true;try{const data=await api.get<PageData<CheckInItem>>('/admin/check-ins',{...filters,schoolId:workspace.schoolId});rows.value=data.items;total.value=data.total}finally{loading.value=false}}
async function moderate(items:CheckInItem[],action:'hide'|'restore'){try{const {value}=await ElMessageBox.prompt(action==='hide'?'请填写照片隐藏原因':'请填写恢复说明',action==='hide'?'隐藏打卡照片':'恢复打卡照片',{inputPattern:/.+/,inputErrorMessage:'必须填写原因'});await api.post('/admin/check-ins/batch-action',{ids:items.map(i=>Number(i.id)),action,reason:value});ElMessage.success('打卡照片状态已更新');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'操作失败')}}
onMounted(load);watch(()=>workspace.schoolId,()=>{filters.page=1;load()})
</script>
<template>
  <section class="paper-card filter-paper"><el-select v-model="filters.status" placeholder="全部照片状态" clearable style="width:160px"><el-option label="已发布" value="published"/><el-option label="已隐藏" value="hidden"/></el-select><el-button type="primary" @click="load">筛选照片</el-button><div style="margin-left:auto"><el-radio-group v-model="viewMode"><el-radio-button value="table">表格</el-radio-button><el-radio-button value="grid">照片墙</el-radio-button></el-radio-group></div></section>
  <section class="paper-card table-paper"><div class="table-toolbar"><h3>打卡拍立得 · {{ total }} 张</h3><div v-if="selected.length" class="toolbar-actions"><el-button type="danger" plain @click="moderate(selected,'hide')">批量隐藏</el-button><el-button type="success" plain @click="moderate(selected,'restore')">批量恢复</el-button></div></div>
  <el-table v-if="viewMode==='table'" v-loading="loading" :data="rows" row-key="id" @selection-change="selected=$event"><el-table-column type="selection" width="45"/><el-table-column label="照片" width="115"><template #default="s"><AuthImage :src="s.row.photoUrl"/></template></el-table-column><el-table-column label="打卡信息" min-width="220"><template #default="s"><strong>{{ s.row.store.name }}</strong><div style="margin-top:5px;color:var(--muted)">{{ s.row.note||'这张照片没有备注' }}</div><div v-if="s.row.moderationReason" style="color:var(--brand);font-size:12px">原因：{{ s.row.moderationReason }}</div></template></el-table-column><el-table-column prop="schoolName" label="学校" min-width="150"/><el-table-column label="用户" width="120"><template #default="s">{{ s.row.user.nickname }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><StatusSticker :status="s.row.status"/></template></el-table-column><el-table-column label="打卡时间" width="170"><template #default="s">{{ new Date(s.row.checkedAt).toLocaleString() }}</template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="s"><el-button link :type="s.row.status==='hidden'?'success':'danger'" @click="moderate([s.row],s.row.status==='hidden'?'restore':'hide')">{{ s.row.status==='hidden'?'恢复':'隐藏' }}</el-button></template></el-table-column></el-table>
  <div v-else class="photo-grid"><article v-for="item in rows" :key="item.id" class="photo-card"><AuthImage :src="item.photoUrl"/><div class="photo-caption">{{ item.store.name }}</div><div class="photo-meta">{{ item.user.nickname }} · {{ item.schoolName }}</div><div class="photo-meta">{{ item.note||'没有留下文字' }}</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:9px"><StatusSticker :status="item.status"/><el-button link :type="item.status==='hidden'?'success':'danger'" @click="moderate([item],item.status==='hidden'?'restore':'hide')">{{ item.status==='hidden'?'恢复':'隐藏' }}</el-button></div></article></div>
  <div class="pagination-row"><el-pagination v-model:current-page="filters.page" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></section>
</template>
