<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, type PageData } from '../api/client'
import StatusSticker from '../components/StatusSticker.vue'
import { useWorkspaceStore } from '../stores/workspace'

interface ReviewItem{id:string;content:string;rating:number;status:string;moderationReason?:string;user:{id:string;nickname:string};store:{id:string;name:string;schoolName:string};createdAt:string}
const workspace=useWorkspaceStore();const filters=reactive({keyword:'',status:'',page:1,pageSize:20});const rows=ref<ReviewItem[]>([]);const total=ref(0);const loading=ref(false);const selected=ref<ReviewItem[]>([])
async function load(){loading.value=true;try{const data=await api.get<PageData<ReviewItem>>('/admin/reviews',{...filters,schoolId:workspace.schoolId});rows.value=data.items;total.value=data.total}finally{loading.value=false}}
async function moderate(items:ReviewItem[],action:'hide'|'restore'){try{const {value}=await ElMessageBox.prompt(action==='hide'?'请填写隐藏原因':'请填写恢复说明',action==='hide'?'隐藏评论':'恢复评论',{inputPattern:/.+/,inputErrorMessage:'必须填写原因'});await api.post('/admin/reviews/batch-action',{ids:items.map(i=>Number(i.id)),action,reason:value});ElMessage.success(action==='hide'?'评论已隐藏':'评论已恢复');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'操作失败')}}
onMounted(load);watch(()=>workspace.schoolId,()=>{filters.page=1;load()})
</script>
<template>
  <section class="paper-card filter-paper"><el-input v-model="filters.keyword" placeholder="评论内容、用户或店铺" clearable style="width:300px" @keyup.enter="load"/><el-select v-model="filters.status" placeholder="全部状态" clearable style="width:140px"><el-option label="已发布" value="published"/><el-option label="已隐藏" value="hidden"/></el-select><el-button type="primary" @click="load">搜索评论</el-button></section>
  <section class="paper-card table-paper"><div class="table-toolbar"><h3>评论便签 · {{ total }} 条</h3><div v-if="selected.length" class="toolbar-actions"><el-button type="danger" plain @click="moderate(selected,'hide')">批量隐藏</el-button><el-button type="success" plain @click="moderate(selected,'restore')">批量恢复</el-button></div></div>
  <el-table v-loading="loading" :data="rows" row-key="id" @selection-change="selected=$event"><el-table-column type="selection" width="45"/><el-table-column label="评论内容" min-width="320"><template #default="s"><div class="note-cell">{{ s.row.content }}</div><div v-if="s.row.moderationReason" style="margin-top:5px;color:var(--brand);font-size:12px">处理原因：{{ s.row.moderationReason }}</div></template></el-table-column><el-table-column label="评分" width="100"><template #default="s"><span style="color:var(--amber)">{{ '★'.repeat(s.row.rating) }}</span></template></el-table-column><el-table-column label="用户" width="130"><template #default="s">{{ s.row.user.nickname }}</template></el-table-column><el-table-column label="学校 / 店铺" min-width="180"><template #default="s">{{ s.row.store.schoolName }}<div style="color:var(--muted);font-size:12px">{{ s.row.store.name }}</div></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><StatusSticker :status="s.row.status"/></template></el-table-column><el-table-column label="发布时间" width="170"><template #default="s">{{ new Date(s.row.createdAt).toLocaleString() }}</template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="s"><el-button link :type="s.row.status==='hidden'?'success':'danger'" @click="moderate([s.row],s.row.status==='hidden'?'restore':'hide')">{{ s.row.status==='hidden'?'恢复':'隐藏' }}</el-button></template></el-table-column></el-table><div class="pagination-row"><el-pagination v-model:current-page="filters.page" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></section>
</template>
