<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, type PageData } from '../api/client'
import StatusSticker from '../components/StatusSticker.vue'
import { useAuthStore } from '../stores/auth'
import { useWorkspaceStore } from '../stores/workspace'

interface StoreItem { id:string;storeCode:string;schoolId:string;schoolName:string;areaId:string;area:string;name:string;category:string;address:string;imageUrl?:string;status:string;score?:number;reviewCount:number;version:number }
const auth=useAuthStore();const workspace=useWorkspaceStore();const loading=ref(false);const rows=ref<StoreItem[]>([]);const total=ref(0);const selected=ref<StoreItem[]>([]);const dialog=ref(false);const editingId=ref('')
const filters=reactive({keyword:'',status:'',page:1,pageSize:20})
const form=reactive({storeCode:'',schoolId:'',areaId:'',name:'',category:'',address:'',imageUrl:'',status:'hidden',version:1})
const isPlatformAdmin=()=>Boolean(auth.admin?.isPlatformAdmin)
const currentSchoolName=()=>workspace.schools.find(item=>item.id===workspace.schoolId)?.name || '未绑定学校'
const selectedSchool=()=>workspace.schools.find(item=>item.id===form.schoolId)
function displayImageUrl(value?:string){if(!value)return '';try{const parsed=new URL(value,window.location.origin);if(parsed.pathname.startsWith('/media/'))return `${parsed.pathname}${parsed.search}`;return value}catch{return value}}
async function load(){loading.value=true;try{const data=await api.get<PageData<StoreItem>>('/admin/stores',{...filters,schoolId:workspace.schoolId});rows.value=data.items;total.value=data.total}finally{loading.value=false}}
function reset(){editingId.value='';Object.assign(form,{storeCode:'',schoolId:workspace.schoolId,areaId:'',name:'',category:'',address:'',imageUrl:'',status:'hidden',version:1});dialog.value=true}
function edit(item:StoreItem){editingId.value=item.id;Object.assign(form,{storeCode:item.storeCode,schoolId:item.schoolId,areaId:item.areaId,name:item.name,category:item.category,address:item.address,imageUrl:item.imageUrl||'',status:item.status,version:item.version});dialog.value=true}
async function save(){if(!form.schoolId)return ElMessage.warning('请先选择要管理的学校');if(!form.areaId)return ElMessage.warning('请先选择该学校的区域');try{if(editingId.value)await api.patch(`/admin/stores/${editingId.value}`,{version:form.version,schoolId:Number(form.schoolId),areaId:Number(form.areaId),name:form.name,category:form.category,address:form.address,imageUrl:form.imageUrl||null,status:form.status});else await api.post('/admin/stores',{...form,schoolId:Number(form.schoolId),areaId:Number(form.areaId),imageUrl:form.imageUrl||null});ElMessage.success('店铺贴纸已保存');dialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}}
async function upload(file:{raw?:File}){if(!file.raw)return;const data=new FormData();data.append('file',file.raw);try{const result=await api.post<{url:string}>('/admin/uploads/images',data);form.imageUrl=result.url;ElMessage.success('图片已上传')}catch(e){ElMessage.error(e instanceof Error?e.message:'上传失败')}}
async function batchStatus(status:string){if(!selected.value.length)return;await ElMessageBox.confirm(`确定修改 ${selected.value.length} 家店铺的状态吗？`,'批量操作',{type:'warning'});try{await Promise.all(selected.value.map(item=>api.patch(`/admin/stores/${item.id}`,{version:item.version,status})));ElMessage.success('批量操作完成');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'操作失败')}}
onMounted(load);watch(()=>workspace.schoolId,()=>{filters.page=1;load()})
</script>
<template>
  <section class="paper-card filter-paper"><el-select v-model="workspace.schoolId" :disabled="!isPlatformAdmin()" placeholder="全部学校" clearable style="width:210px"><el-option label="全部学校" value=""/><el-option v-for="item in workspace.schools" :key="item.id" :label="item.name" :value="item.id"/></el-select><span v-if="!isPlatformAdmin()" class="filter-note">当前学校：{{ currentSchoolName() }}</span><el-input v-model="filters.keyword" placeholder="搜索店铺名称、编码或地址" clearable style="width:280px" @keyup.enter="load"/><el-select v-model="filters.status" placeholder="全部状态" clearable style="width:140px"><el-option label="正常" value="active"/><el-option label="隐藏" value="hidden"/><el-option label="关闭" value="closed"/></el-select><el-button type="primary" @click="load">查找贴纸</el-button></section>
  <section class="paper-card table-paper"><div class="table-toolbar"><h3>店铺贴纸册 · {{ total }} 家</h3><div class="toolbar-actions"><template v-if="selected.length"><el-button type="success" plain @click="batchStatus('active')">批量上架</el-button><el-button type="warning" plain @click="batchStatus('hidden')">批量隐藏</el-button><el-button type="danger" plain @click="batchStatus('closed')">批量关闭</el-button></template><el-button type="primary" @click="reset">＋ 新增店铺</el-button></div></div>
    <el-table v-loading="loading" :data="rows" row-key="id" @selection-change="selected=$event"><el-table-column type="selection" width="45"/><el-table-column label="照片" width="100"><template #default="s"><div class="polaroid"><img v-if="s.row.imageUrl" :src="displayImageUrl(s.row.imageUrl)" alt="店铺图片"/><div v-else class="image-fallback">暂无图片</div></div></template></el-table-column><el-table-column label="店铺" min-width="180"><template #default="s"><strong>{{ s.row.name }}</strong><div class="mono">{{ s.row.storeCode }}</div></template></el-table-column><el-table-column label="学校 / 区域" min-width="170"><template #default="s">{{ s.row.schoolName }}<div style="color:var(--muted);font-size:12px">{{ s.row.area }}</div></template></el-table-column><el-table-column prop="category" label="分类" width="130"/><el-table-column label="评分" width="100"><template #default="s">★ {{ s.row.score??'—' }} <small>({{ s.row.reviewCount }})</small></template></el-table-column><el-table-column label="状态" width="95"><template #default="s"><StatusSticker :status="s.row.status"/></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button></template></el-table-column></el-table>
    <div class="pagination-row"><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.pageSize" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></section>
  <el-dialog v-model="dialog" :title="editingId?'编辑店铺贴纸':'贴一家新店铺'" width="720px"><el-form label-position="top"><div class="form-grid"><el-form-item label="店铺编码"><el-input v-model="form.storeCode" :disabled="Boolean(editingId)"/></el-form-item><el-form-item label="店铺名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="学校"><el-select v-model="form.schoolId" filterable :disabled="!isPlatformAdmin()" @change="form.areaId=''" style="width:100%"><el-option v-for="item in workspace.schools" :key="item.id" :label="item.name" :value="item.id"/></el-select><small class="form-help">{{ isPlatformAdmin() ? '系统管理员可将店铺归档到任意学校' : `校区管理员固定管理：${currentSchoolName()}` }}</small></el-form-item><el-form-item label="区域"><el-select v-model="form.areaId" style="width:100%"><el-option v-for="area in selectedSchool()?.areas||[]" :key="area.id" :label="area.name" :value="area.id"/></el-select></el-form-item><el-form-item label="分类"><el-input v-model="form.category"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="正常上架" value="active"/><el-option label="暂时隐藏" value="hidden"/><el-option label="已经关闭" value="closed"/></el-select></el-form-item><el-form-item label="详细地址" class="wide"><el-input v-model="form.address"/></el-form-item><el-form-item label="图片地址" class="wide"><el-input v-model="form.imageUrl" placeholder="可填写 URL 或使用下方上传"/></el-form-item><el-form-item class="wide"><el-upload :auto-upload="false" :show-file-list="false" accept="image/jpeg,image/png,image/webp" @change="upload"><el-button>选择店铺图片</el-button></el-upload></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存贴纸</el-button></template></el-dialog>
</template>
