<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, type PageData } from '../api/client'
import StatusSticker from '../components/StatusSticker.vue'
import { useAuthStore } from '../stores/auth'
import { useWorkspaceStore } from '../stores/workspace'

interface Restriction {commentBlocked:boolean;commentBlockReason?:string;imageUploadBlocked:boolean;imageUploadBlockReason?:string}
interface UserItem{id:string;externalId:string;nickname:string;schoolId?:string;schoolName?:string;level:number;status:string;reviewCount:number;checkInCount:number;createdAt:string;lastLoginAt?:string;restriction:Restriction}
const router=useRouter();const auth=useAuthStore();const workspace=useWorkspaceStore();const filters=reactive({keyword:'',status:'',page:1,pageSize:20});const rows=ref<UserItem[]>([]);const total=ref(0);const loading=ref(false);const selected=ref<UserItem[]>([]);const drawer=ref(false);const detail=ref<Record<string,any>|null>(null);const restrictionDialog=ref(false)
const restrictionForm=reactive({userId:'',type:'comment' as 'comment'|'image_upload',reason:'',blockedUntil:''})
async function load(){loading.value=true;try{const data=await api.get<PageData<UserItem>>('/admin/users',{...filters,schoolId:workspace.schoolId});rows.value=data.items;total.value=data.total}finally{loading.value=false}}
async function view(item:UserItem){detail.value=await api.get(`/admin/users/${item.id}`);drawer.value=true}
function openRestriction(item:UserItem,type:'comment'|'image_upload'){Object.assign(restrictionForm,{userId:item.id,type,reason:'',blockedUntil:''});restrictionDialog.value=true}
async function saveRestriction(){if(!restrictionForm.reason.trim())return ElMessage.warning('请填写限制原因');try{await api.post(`/admin/users/${restrictionForm.userId}/restrictions`,{restrictionType:restrictionForm.type,blocked:true,reason:restrictionForm.reason,blockedUntil:restrictionForm.blockedUntil?new Date(restrictionForm.blockedUntil).toISOString():null});ElMessage.success('用户限制已设置');restrictionDialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'操作失败')}}
async function unblock(item:UserItem,type:'comment'|'image_upload'){try{const {value}=await ElMessageBox.prompt('请填写解除原因','解除用户限制',{inputPattern:/.+/,inputErrorMessage:'必须填写原因'});await api.post(`/admin/users/${item.id}/restrictions`,{restrictionType:type,blocked:false,reason:value});ElMessage.success('用户限制已解除');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'操作失败')}}
async function batch(action:string){if(!selected.value.length)return;try{const {value}=await ElMessageBox.prompt(`将对 ${selected.value.length} 位用户执行操作，请填写原因`,'批量用户管理',{inputPattern:/.+/,inputErrorMessage:'必须填写原因'});await api.post('/admin/users/batch-action',{ids:selected.value.map(i=>Number(i.id)),action,reason:value});ElMessage.success('批量操作完成');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'操作失败')}}
function openUserContent(item:UserItem, target:'reviews'|'check-ins'){router.push({path:`/${target}`,query:{userId:item.id,schoolId:item.schoolId||undefined}})}
onMounted(load);watch(()=>workspace.schoolId,()=>{filters.page=1;load()})
</script>
<template>
  <section class="paper-card filter-paper"><el-select v-model="workspace.schoolId" :disabled="!auth.admin?.isPlatformAdmin" placeholder="全部学校" clearable style="width:210px"><el-option label="全部学校" value=""/><el-option v-for="school in workspace.schools" :key="school.id" :label="school.name" :value="school.id"/></el-select><el-input v-model="filters.keyword" placeholder="昵称或 externalId" clearable style="width:260px" @keyup.enter="load"/><el-select v-model="filters.status" placeholder="全部账号状态" clearable style="width:150px"><el-option label="正常" value="active"/><el-option label="已禁用" value="disabled"/></el-select><el-button type="primary" @click="load">查找用户</el-button></section>
  <section class="paper-card table-paper"><div class="table-toolbar"><h3>用户档案卡 · {{ total }} 人</h3><div v-if="selected.length" class="toolbar-actions"><el-button type="danger" plain @click="batch('disable')">批量禁用</el-button><el-button type="warning" plain @click="batch('block_comment')">批量禁评</el-button><el-button type="warning" plain @click="batch('block_image')">批量禁图</el-button></div></div>
  <el-table v-loading="loading" :data="rows" row-key="id" @selection-change="selected=$event"><el-table-column type="selection" width="45"/><el-table-column label="用户" min-width="170"><template #default="s"><strong>{{ s.row.nickname }}</strong><div class="mono">ID {{ s.row.id }} · {{ s.row.externalId }}</div></template></el-table-column><el-table-column prop="schoolName" label="学校" min-width="150"/><el-table-column label="内容" width="130"><template #default="s">评论 {{ s.row.reviewCount }} · 打卡 {{ s.row.checkInCount }}</template></el-table-column><el-table-column label="账号" width="90"><template #default="s"><StatusSticker :status="s.row.status"/></template></el-table-column><el-table-column label="限制状态" min-width="180"><template #default="s"><span v-if="!s.row.restriction.commentBlocked&&!s.row.restriction.imageUploadBlocked" class="status-sticker is-active">无限制</span><span v-if="s.row.restriction.commentBlocked" class="status-sticker is-hidden">禁止评论</span> <span v-if="s.row.restriction.imageUploadBlocked" class="status-sticker is-hidden">禁止上传</span></template></el-table-column><el-table-column label="最后登录" width="170"><template #default="s">{{ s.row.lastLoginAt?new Date(s.row.lastLoginAt).toLocaleString():'—' }}</template></el-table-column><el-table-column label="操作" width="340" fixed="right"><template #default="s"><el-button link type="primary" @click="view(s.row)">档案</el-button><el-button link type="primary" @click="openUserContent(s.row,'reviews')">评论</el-button><el-button link type="primary" @click="openUserContent(s.row,'check-ins')">打卡</el-button><el-button link :type="s.row.restriction.commentBlocked?'success':'warning'" @click="s.row.restriction.commentBlocked?unblock(s.row,'comment'):openRestriction(s.row,'comment')">{{ s.row.restriction.commentBlocked?'恢复评论':'禁止评论' }}</el-button><el-button link :type="s.row.restriction.imageUploadBlocked?'success':'danger'" @click="s.row.restriction.imageUploadBlocked?unblock(s.row,'image_upload'):openRestriction(s.row,'image_upload')">{{ s.row.restriction.imageUploadBlocked?'恢复上传':'禁止上传' }}</el-button></template></el-table-column></el-table>
  <div class="pagination-row"><el-pagination v-model:current-page="filters.page" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></section>
  <el-drawer v-model="drawer" title="用户档案卡" size="560px"><template v-if="detail"><dl class="detail-list"><dt>昵称</dt><dd>{{ detail.nickname }}</dd><dt>externalId</dt><dd class="mono">{{ detail.externalId }}</dd><dt>学校</dt><dd>{{ detail.schoolName||'未选择' }}</dd><dt>账号状态</dt><dd><StatusSticker :status="detail.status"/></dd><dt>注册时间</dt><dd>{{ new Date(detail.createdAt).toLocaleString() }}</dd></dl><h3 style="margin:24px 8px 12px">最近评论</h3><div class="activity-list"><div v-for="item in detail.reviews" :key="item.id" class="activity-item">★ {{ item.rating }} · {{ item.content }}</div><div v-if="!detail.reviews.length" class="activity-item">暂无评论</div></div><h3 style="margin:24px 8px 12px">最近打卡</h3><div class="activity-list"><div v-for="item in detail.checkIns" :key="item.id" class="activity-item">{{ item.note||'无备注' }} · {{ item.status }}</div><div v-if="!detail.checkIns.length" class="activity-item">暂无打卡</div></div></template></el-drawer>
  <el-dialog v-model="restrictionDialog" :title="restrictionForm.type==='comment'?'设置评论限制':'设置图片上传限制'" width="520px"><el-form label-position="top"><el-form-item label="限制原因"><el-input v-model="restrictionForm.reason" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item><el-form-item label="解除时间（留空表示永久限制）"><el-date-picker v-model="restrictionForm.blockedUntil" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="永久限制" style="width:100%"/></el-form-item></el-form><template #footer><el-button @click="restrictionDialog=false">取消</el-button><el-button type="primary" @click="saveRestriction">确认限制</el-button></template></el-dialog>
</template>
